# Generated by Django 5.1.7 on 2025-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_userdetails_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userdetails',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
