# Generated by Django 5.1.7 on 2025-03-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.IntegerField()),
                ('subject2', models.IntegerField()),
                ('subject3', models.IntegerField()),
                ('subject4', models.IntegerField()),
                ('subject5', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testmarks', to='Student.studentdetails')),
            ],
        ),
    ]
